version: "3.8"
services:
  backend:
    build: .
    container_name: fastapi_groq_supabase
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./tmp_files:/app/tmp_files
    restart: unless-stopped
